### ISSUE TITLE
Getting the current user's info is missing the email field

### ISSUE THREAD

**Issue by SiongSng** [Lipoic/Lipoic-Backend#14]
![image](https://user-images.githubusercontent.com/48402225/196912512-6da1c423-5e19-4110-bc71-ed05901bec03.png)

**Comment by lumynou5** [comment]
Further information needed.

**Comment by SiongSng** [comment]
@Luminous-Coder

Get current user information API (if authenticated).
The API should provide more detailed information like email, connect accounts, etc.

See also the code:
https://github.com/Lipoic/Lipoic-Backend/blob/d7dc8d2fd5e34a0c2b8bdcf41ade9e6c3a80cfd1/src/router/api/user/index.ts#L40-L43

https://github.com/Lipoic/Lipoic-Backend/blob/d7dc8d2fd5e34a0c2b8bdcf41ade9e6c3a80cfd1/src/model/auth/user.ts#L94-L104
