### ISSUE TITLE
Gitignore contains `.vscode`

### ISSUE THREAD

**Issue by lumynou5** [Lipoic/Lipoic-Backend#23]
Developers should add files generated by IDE they use to the global gitignore.

e.g.
```sh
git config --global core.excludesFile "~/.gitignore"
```
```gitignore
# ~/.gitignore

.vscode/
.idea/
# etc.
```

**Comment by SiongSng** [comment]
It already has, right?
https://github.com/Lipoic/Lipoic-Backend/blob/2ac2dadc5fed883730bbd1477ec07f2adcdb61e3/.gitignore#L110

**Comment by lumynou5** [comment]
No, you didn't get it.

**Comment by SiongSng** [comment]
那不然你的意思是指？

**Comment by lumynou5** [comment]
窩明明就有打範例..

**Comment by SiongSng** [comment]
你是說差了一個斜線？

```diff
-.vscode
+.vscode/
```

**Comment by lumynou5** [comment]
Please do not skip the word "global"...
Since every developer may use different tools, the gitignore shouldn't contain these files; the tools in the world are uncountable. Adding these files is bad; ignoring them in the project scope is not good.

**Comment by lumynou5** [comment]
doesn't very matter
